### ISSUE TITLE
Refactor requirements to keep database technologies separate

### ISSUE THREAD

**Issue by isedwards** [opencdms/pyopencdms#2]
By default, `pyopencdms` will not have any specific database technologies as default requirements.  It should be possible to use the package with the Climate Data Model exchange format (JSON) without any database backend.

Therefore we should refactor our requirements into a `requirements` directory along the lines of:

```
requirements/
    db/
        postgres.txt
        mysql.txt
    provider/
        provider_opencdmsdb.txt
        provider_surface
    base.txt
    prod.txt
```

We can be flexible on requirement versions in most requirements files and only freeze requirements in `prod.txt`

To avoid duplicating our requirements we can reference these requirements files in setup.py:
```
# setup.py
from setuptools import setup

with open("requirements/base.txt") as f:
    base_requirements = f.read().splitlines()

with open("requirements/extras.txt") as f:
    extras_requirements = f.read().splitlines()

setup(
    name="myproject",
    version="0.1",
    install_requires=base_requirements,
    extras_require={
        "extras": extras_requirements
    },
    ...
)
```

This will allow users to install the optional dependencies that they need when running setup.

Also, `opencdms-test-data` requirements currently depends on a dev branch (52-pygeoapi-provider-plugin-for-surface-cdms) of the old opencdms-dev version of pyopencdms:

https://github.com/opencdms/opencdms-test-data/blob/main/requirements_dev.txt#L9

**Comment by chinedu117** [comment]
I was wondering where the extras.txt file would come from. How would the users indicate the database dependencies they need ?

**Comment by isedwards** [comment]
Fixed by https://github.com/opencdms/opencdms-test-data/pull/55
